sudo: required
dist: xenial
language: python
python:
  - 3.9
os:
  - linux
services:
  - docker
before_install:
  - chmod +x packages.sh
install: ./packages.sh
deploy:
  provider: script
  script: 
    - kubectl apply -f deployment.yml
  on:
   branch: master
