sudo: required
dist: xenial
language: python
python:
  - 3.9
os:
  - linux
services:
  - docker
before_install:
  - chmod +x packages.sh
  - chmod +x deploy.sh
install: ./packages.sh

after_success:
  - echo "deployment started"

deploy:
  provider: script
  script: deploy.sh
  on:
    branch: main



