apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-micro
  labels:
    app: flask
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
      - name: flask-micro
        image: srirammk18/flask-prod:5
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
